name: Scheduled Stock Sync

on:
  # runs every 5 minutes
  schedule:
    - cron: '*/5 * * * *'
  # also allow manual trigger
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'      # or your preferred LTS

      - name: Install dependencies
        run: npm ci

      - name: Run the sync
        env:
          SS_USERNAME: ${{ secrets.SS_USERNAME }}
          SS_PASSWORD: ${{ secrets.SS_PASSWORD }}
          SS_CUSTOMER_NUMBER: ${{ secrets.SS_CUSTOMER_NUMBER }}
          SS_SOURCE: ${{ secrets.SS_SOURCE }}
        run: node src/sync.js

      - name: Upload CSV artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: volusion-upload
          path: volusion-upload.csv
